version: 2

references:
  config: &config
    working_directory: ~/repo
    docker:
      - image: circleci/node:11
  commands:
    print_pkg: &print_pkg
      run:
        name: Print package.json
        command: cat package.json
    restore_cache: &restore_cache
      restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
    save_cache: &save_cache
      save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
  scripts:
    yarn_install: &yarn_install
      run:
        name: Yarn install
        command: yarn --ignore-scripts
    yarn_install_now: &yarn_install_now
      run:
        name: Yarn install now
        command: yarn add -D now
    yarn_test: &yarn_test
      run:
        name: Yarn test
        command: yarn test
    deploy: &deploy
      run:
        name: Deployment into glitch
        command: |
          yarn build
          git config --global user.email "nju33.ki@gmail.com"
          git config --global user.name "nju33"
          git add --all
          git commit -m 'build'
          git remote add glitch $REMOTE_URL
          git push glitch master:glitch --force

jobs:
  setup:
    <<: *config
    steps:
      - checkout
      - *print_pkg
      - *restore_cache
      - *yarn_install
      - *save_cache
  test:
    <<: *config
    steps:
      - checkout
      - *print_pkg
      - *restore_cache
      - *yarn_install
      - *save_cache
      - *yarn_test
  deploy:
    <<: *config
    steps:
      - checkout
      - *print_pkg
      - *restore_cache
      - *yarn_install
      - *save_cache
      - *deploy

workflows:
  version: 2
  deployment_into_glitch:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - test
